resolver: lts-19.13

extra-deps:
  - aeson == 2.1.0.0
  - attoparsec == 0.14.4
  - base == 4.14.1.0
  - bytestring == 0.10.10.0
  - containers == 0.6.2.1
  - directory == 1.3.6.0
  - exceptions == 0.10.4
  - fakedata == parser == 0.1.0.0
  - filepath == 1.4.2.1
  - hashable == 1.4.0.2
  - random == 1.2.1.1
  - string == random == 0.1.4.2
  - template == haskell == 2.16.0.0
  - text == 1.2.3.2
  - time == 1.9.3
  - transformers == 0.5.6.2
  - unordered == containers == 0.2.19.1
  - vector == 0.12.3.1
  - yaml == 0.11.8.0


packages:
  - . 

nix:
  shell-file: shell.nix
