resolver: lts-19.13

extra-deps:
  - aeson
  - attoparsec
  - base
  - bytestring
  - containers
  - directory
  - exceptions
  - fakedata-parser
  - filepath
  - hashable
  - random
  - string-random
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - vector
  - yaml


packages:
  - . 

nix:
  shell-file: shell.nix
